name: quantum_dashboard
description: "Quantum Works Employee Dashboard"
publish_to: "none" 

version: 1.0.3+7 

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  in_app_update: ^4.2.3
  url_launcher: ^6.3.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  timeline_tile: ^2.0.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_filex: ^4.7.0
  dio: ^5.9.0
  image: ^4.1.7
  google_nav_bar: ^5.0.7
  lottie: ^3.3.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_animate: ^4.5.2
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.3.0
  geolocator: ^14.0.2
  logger: ^2.4.0
  fl_chart: ^0.69.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  csv: ^6.0.0
  file_picker: ^8.1.2
  excel: ^4.0.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/avatars/
    - assets/illustrations/
    - assets/illustrations/changepasswordimage.png
    - assets/illustrations/loading.json
    - shorebird.yaml

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
